[program:profiles_api]
command=/usr/local/virtualenvs/profiles_api/bin/gunicorn --bind 127.0.0.1:9000 profiles_project.wsgi:application
directory=/usr/local/apps/profiles-rest-api/src/profiles_project
user=root
environment=DJANGO_SECRET_KEY="CHANGE_ME"
autostart=true
autorestart=true
stdout_logfile=/var/log/profiles_api.log
stderr_logfile=/var/log/profiles_api_err.log
