# Generated by Django 6.1 on 2026-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auditlog_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('ACCOUNT_CHANGE', 'Account Change'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('ACCOUNT_CHANGE', 'Account Change'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access')], max_length=50),
        ),
    ]
