# Generated by Django 6.1 on 2026-09-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_alter_auditlog_action_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='request_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
