# Generated by Django 6.1 on 2026-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_securityevent_ip_address_securityevent_request_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('BRUTE_FORCE_DETECTED', 'Brute Force Detected'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('ACCOUNT_CHANGE', 'Account Change'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access')], max_length=50),
        ),
    ]
