# Generated by Django 6.1 on 2026-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('BRUTE_FORCE_DETECTED', 'Brute Force Detected'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('ACCOUNT_CHANGE', 'Account Change'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('SUSPICIOUS_IP_DETECTED', 'Suspicious IP Detected')], max_length=50),
        ),
    ]
